# -*- coding: utf-8 -*-
"""Sprint 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U4FDVYYOQ0F19RzY3_M1jGn4q_WCqXYF

## Sprint 3
"""

pip install joblib

from joblib import dump

# Save the trained model to a file
dump(random, 'random_forest_model.pkl')

import sklearn
print(sklearn.__version__)